apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdp-eks-dev-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ebrahimmohamedalsaeed-collab/CloudDevOpsProject.git
    targetRevision: main
    path: k8s

  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

